#include "base.hpp"

#include <stdio.h>

Slice<u8> file_read(String path, Arena* arena);
i64 file_write(String path, Slice<u8> data);

constexpr usize SCRATCH_ARENA_SIZE = 8 * 1024LL * 1024LL;
thread_local Arena scratch_arena = {};

void init(){
	auto buf = Slice<u8>{new u8[SCRATCH_ARENA_SIZE], SCRATCH_ARENA_SIZE};
	scratch_arena = arena_from_buffer(buf);
}

struct CRC32_Table {
	u32 entries[256];
};

void crc32_fill_table(CRC32_Table* table, u32 polynomial) {
	constexpr u32 bit_width = sizeof(u32) * 8;
	constexpr u32 top_bit = (u32(1) << (bit_width - 1));
    u32 remainder = 0;

    for (int dividend = 0; dividend < 256; dividend += 1) {
        remainder = dividend << (bit_width - 8);

        for (u8 bit = 8; bit > 0; --bit){
            if (remainder & top_bit) {
                remainder = (remainder << 1) ^ polynomial;
            }
            else {
                remainder = (remainder << 1);
            }
        }
        table->entries[dividend] = remainder;
    }
}

struct StringBuilder {
	List<u8> buf;

	bool append(String str){
		if((this->buf.len + str.len) >= this->buf.cap){
			if(!this->buf.resize(max<usize>(16, this->buf.len + str.len))){
				return false;
			}
		}

		mem_copy(&this->buf.data[this->buf.len], str.data, str.len);
		this->buf.len += str.len;
		return true;
	}

	String string(){
		return String((char const*)this->buf.data, this->buf.len);
	}

	Slice<u8> bytes(){
		return this->buf.slice();
	}
};

StringBuilder builder_create(usize cap, Arena* arena){
	StringBuilder sb = { make_list<u8>(arena, 0, cap) };
	return sb;
}

int main(){
	init();

	auto allocator = &scratch_arena;

	/* Generate CRC32 */ {
		constexpr u32 CRC32_POLYNOMIAL = 0xEDB88320;

		auto sb = builder_create(512, allocator);
		auto base_impl = String(file_read("assets/crc32.cpp", &scratch_arena));
		ensure(base_impl.data, "Failed to read crc32 file.");

		auto poly_decl = arena_printf(&scratch_arena, "constexpr u32 CRC32_POLYNOMIAL = 0x%08x;\n", CRC32_POLYNOMIAL);

		auto table = CRC32_Table{0};
		crc32_fill_table(&table, CRC32_POLYNOMIAL);

		sb.append(arena_printf(&scratch_arena, "/* Generated by %s */\n", __FILE__));
		sb.append("constexpr u32 crc32_lut[] = {\n\t");
		for(usize i = 0; i < 256; i += 1){
			if(i && (i % 8 == 0)){
				sb.append("\n\t");
			}
			sb.append(arena_printf(&scratch_arena, "0x%08x,", u32(table.entries[i])));
		}
		sb.append("\n};\n");

		sb.append(poly_decl);
		sb.append(base_impl);

		i64 written = file_write("crc32.gen.cpp", sb.bytes());
		printf("-> Generated crc32.gen.cpp (%.1g KiB)\n", f64(written) / f64(1024));

		ensure(written > 0, "Failed to write file");
		scratch_arena.reset();
	}
}

i64 file_write(String path, Slice<u8> buf){
	FILE* fd = nullptr;

	/* Open file */ {
		auto reg = arena_region_begin(&scratch_arena);
		auto path_null = clone_to_cstring(path, &scratch_arena);

		fd = fopen(path_null, "wb");
		arena_region_end(reg);

		if(fd == nullptr){ return -1; }
	}

	return i64(fwrite(buf.data, 1, buf.len, fd));
}

Slice<u8> file_read(String path, Arena* arena){
	FILE* fd = nullptr;
	usize file_size = 0;
	Slice<u8> buf = {};

	/* Open file */ {
		auto reg = arena_region_begin(&scratch_arena);
		auto path_null = clone_to_cstring(path, &scratch_arena);

		fd = fopen(path_null, "rb");
		arena_region_end(reg);

		if(fd == nullptr){ return {}; }
	}

	fseek(fd, 0, SEEK_END);
	usize end = ftell(fd);
	rewind(fd);
	usize begin = ftell(fd);
	file_size = end - begin;

	buf = make_slice<u8>(arena, file_size + 1);
	if(buf.len != (file_size + 1)){
		goto exit;
	}
	buf.len -= 1;

	fread(buf.data, 1, file_size, fd);

exit:
	fclose(fd);
	return buf;
}
